# File for global variables

TRAIN_IN_SIZE = ()
TRAIN_OUT_SIZE = ()

TEST_IN_SIZE = ()
TEST_OUT_SIZE = ()

SAMPLING_RATE = 22050
SECONDS = 5
BINS_PER_OCTAVE = 36
START_TOKENS = 500
END_TOKENS = -500
